<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommandSystem.Commands\CommandSystem.Commands.csproj" />
    <ProjectReference Include="..\CommandSystem.Console\CommandSystem.Console.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AlexeyKuznetsov">
      <HintPath>..\..\AlexeyKuznetsov\AlexeyKuznetsov\bin\Debug\net8.0\AlexeyKuznetsov.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
