<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UnityCommander\UnityCommander\UnityCommander.Logging\UnityCommander.Logging.csproj" />
    <ProjectReference Include="..\CommandSystem.Core\CommandSystem.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UndoRedo\" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /d &quot;$(TargetPath)&quot; &quot;$(SolutionDir)..\_builds\&quot;" />
	</Target>
</Project>
