<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommandSystem.Console\CommandSystem.Console.csproj" />
    <ProjectReference Include="..\CommandSystem.Gui\CommandSystem.Gui.csproj" />
    <ProjectReference Include="..\UnityCommander.SystemMetrics\UnityCommander.SystemMetrics.csproj" />
  </ItemGroup>
	<!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(SolutionDir)CommandSystem.CLI\bin\Debug\net8.0\cmd&quot; /Y /I /E" />
	</Target>-->

</Project>
