<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net9.0;net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ViewModels\o0ysosmq.ef1~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WPF" Version="5.0.56" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AlexeyKuznetsov\AlexeyKuznetsov\AlexeyKuznetsov.csproj" />
    <ProjectReference Include="..\CommandSystem.Gui\CommandSystem.Gui.csproj" />
    <ProjectReference Include="..\UnityCommander.Copying\UnityCommander.Copying.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityGraph">
      <HintPath>..\..\_builds\UnityGraph.dll</HintPath>
    </Reference>
    <Reference Include="UnityGraph.WPF">
      <HintPath>..\..\_builds\UnityGraph.WPF.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
