<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AlexeyKuznetsov\AlexeyKuznetsov\AlexeyKuznetsov.csproj" />
    <ProjectReference Include="..\CommandSystem.Gui\CommandSystem.Gui.csproj" />
    <ProjectReference Include="..\UnityCommander.Copying\UnityCommander.Copying.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

</Project>
